tooling: Fix installing ROS 2 depends on BeagleBone AI
Installation error was:

  Installing rosdep packages...
  ERROR: the following packages/stacks could not have their rosdep keys resolved
  to system dependencies:
  ros2doctor: No definition of [python3-ifcfg] for OS version [bullseye]